<?php
return [
    'invokables' => [
        'FormButton'            => 'PrxBootstrap\Form\View\Helper\FormButton',
        'FormColor'             => 'PrxBootstrap\Form\View\Helper\FormColor',
        'FormDate'              => 'PrxBootstrap\Form\View\Helper\FormDate',
        'FormDateTime'          => 'PrxBootstrap\Form\View\Helper\FormDateTime',
        'FormDateTimeLocal'     => 'PrxBootstrap\Form\View\Helper\FormDateTimeLocal',
        'FormEmail'             => 'PrxBootstrap\Form\View\Helper\FormEmail',
        'FormInput'             => 'PrxBootstrap\Form\View\Helper\FormInput',
        'FormMonth'             => 'PrxBootstrap\Form\View\Helper\FormMonth',
        'FormMultiCheckbox'     => 'PrxBootstrap\Form\View\Helper\FormMultiCheckbox',
        'FormNumber'            => 'PrxBootstrap\Form\View\Helper\FormNumber',
        'FormPassword'          => 'PrxBootstrap\Form\View\Helper\FormPassword',
        'FormRadio'             => 'PrxBootstrap\Form\View\Helper\FormRadio',
        'FormRow'               => 'PrxBootstrap\Form\View\Helper\FormRow',
        'FormSelect'            => 'PrxBootstrap\Form\View\Helper\FormSelect',
        'FormSubmit'            => 'PrxBootstrap\Form\View\Helper\FormSubmit',
        'FormText'              => 'PrxBootstrap\Form\View\Helper\FormText',
        'FormTextarea'          => 'PrxBootstrap\Form\View\Helper\FormTextarea',
        'FormTime'              => 'PrxBootstrap\Form\View\Helper\FormTime',
        'FormUrl'               => 'PrxBootstrap\Form\View\Helper\FormUrl',
        'FormWeek'              => 'PrxBootstrap\Form\View\Helper\FormWeek',
    ],
];
